# Generated by Django 4.0.1 on 2023-01-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactmarble'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactmarble',
        ),
    ]
